const exerciseDB = [
    // Chest
    { id: "e1", name: "Barbell Bench Press", muscle: "Chest", equipment: "Barbell", level: "Beginner" },
    { id: "e2", name: "Incline Barbell Bench Press", muscle: "Chest", equipment: "Barbell", level: "Intermediate" },
    { id: "e3", name: "Decline Barbell Bench Press", muscle: "Chest", equipment: "Barbell", level: "Advanced" },
    { id: "e4", name: "Dumbbell Bench Press", muscle: "Chest", equipment: "Dumbbell", level: "Beginner" },
    { id: "e5", name: "Incline Dumbbell Press", muscle: "Chest", equipment: "Dumbbell", level: "Intermediate" },
    { id: "e6", name: "Decline Dumbbell Press", muscle: "Chest", equipment: "Dumbbell", level: "Advanced" },
    { id: "e7", name: "Push-Up", muscle: "Chest", equipment: "Bodyweight", level: "Beginner" },
    { id: "e8", name: "Decline Push-Up", muscle: "Chest", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e9", name: "Incline Push-Up", muscle: "Chest", equipment: "Bodyweight", level: "Beginner" },
    { id: "e106", name: "Knee Push-Up", muscle: "Chest", equipment: "Bodyweight", level: "Beginner" },
    { id: "e107", name: "Wall Push-Up", muscle: "Chest", equipment: "Bodyweight", level: "Beginner" },
    { id: "e10", name: "Plyometric Push-Up", muscle: "Chest", equipment: "Bodyweight", level: "Advanced" },
    { id: "e11", name: "Cable Crossover", muscle: "Chest", equipment: "Cable", level: "Intermediate" },
    { id: "e12", name: "Low Cable Crossover", muscle: "Chest", equipment: "Cable", level: "Intermediate" },
    { id: "e13", name: "Pec Deck Machine", muscle: "Chest", equipment: "Machine", level: "Beginner" },
    { id: "e14", name: "Chest Press Machine", muscle: "Chest", equipment: "Machine", level: "Beginner" },
    { id: "e15", name: "Dumbbell Flyes", muscle: "Chest", equipment: "Dumbbell", level: "Intermediate" },
    { id: "e16", name: "Incline Dumbbell Flyes", muscle: "Chest", equipment: "Dumbbell", level: "Intermediate" },
    { id: "e17", name: "Dumbbell Pullover", muscle: "Chest", equipment: "Dumbbell", level: "Advanced" },
    { id: "e18", name: "Svend Press", muscle: "Chest", equipment: "Dumbbell", level: "Intermediate" },

    // Back
    { id: "e19", name: "Barbell Deadlift", muscle: "Back", equipment: "Barbell", level: "Intermediate" },
    { id: "e20", name: "Sumo Deadlift", muscle: "Back", equipment: "Barbell", level: "Advanced" },
    { id: "e21", name: "Pull-Up", muscle: "Back", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e108", name: "Assisted Pull-Up", muscle: "Back", equipment: "Machine", level: "Beginner" },
    { id: "e22", name: "Weighted Pull-Up", muscle: "Back", equipment: "Bodyweight", level: "Advanced" },
    { id: "e23", name: "Chin-Up", muscle: "Back", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e24", name: "Lat Pulldown (Wide)", muscle: "Back", equipment: "Machine", level: "Beginner" },
    { id: "e25", name: "Lat Pulldown (Close Grip)", muscle: "Back", equipment: "Machine", level: "Beginner" },
    { id: "e26", name: "Barbell Row", muscle: "Back", equipment: "Barbell", level: "Intermediate" },
    { id: "e27", name: "Pendlay Row", muscle: "Back", equipment: "Barbell", level: "Advanced" },
    { id: "e28", name: "Seated Cable Row", muscle: "Back", equipment: "Cable", level: "Beginner" },
    { id: "e29", name: "Single Arm Dumbbell Row", muscle: "Back", equipment: "Dumbbell", level: "Beginner" },
    { id: "e30", name: "T-Bar Row", muscle: "Back", equipment: "Machine", level: "Intermediate" },
    { id: "e31", name: "Inverted Row", muscle: "Back", equipment: "Bodyweight", level: "Beginner" },
    { id: "e32", name: "Straight Arm Pulldown", muscle: "Back", equipment: "Cable", level: "Intermediate" },
    { id: "e33", name: "Good Mornings", muscle: "Back", equipment: "Barbell", level: "Intermediate" },
    { id: "e34", name: "Hyperextension", muscle: "Back", equipment: "Machine", level: "Beginner" },

    // Shoulders
    { id: "e35", name: "Overhead Press", muscle: "Shoulders", equipment: "Barbell", level: "Intermediate" },
    { id: "e36", name: "Push Press", muscle: "Shoulders", equipment: "Barbell", level: "Advanced" },
    { id: "e37", name: "Dumbbell Shoulder Press", muscle: "Shoulders", equipment: "Dumbbell", level: "Beginner" },
    { id: "e38", name: "Arnold Press", muscle: "Shoulders", equipment: "Dumbbell", level: "Intermediate" },
    { id: "e39", name: "Lateral Raise", muscle: "Shoulders", equipment: "Dumbbell", level: "Beginner" },
    { id: "e40", name: "Cable Lateral Raise", muscle: "Shoulders", equipment: "Cable", level: "Intermediate" },
    { id: "e41", name: "Front Raise", muscle: "Shoulders", equipment: "Dumbbell", level: "Beginner" },
    { id: "e42", name: "Reverse Pec Deck", muscle: "Shoulders", equipment: "Machine", level: "Beginner" },
    { id: "e43", name: "Face Pull", muscle: "Shoulders", equipment: "Cable", level: "Beginner" },
    { id: "e44", name: "Pike Push-Up", muscle: "Shoulders", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e45", name: "Handstand Push-Up", muscle: "Shoulders", equipment: "Bodyweight", level: "Advanced" },
    { id: "e46", name: "Upright Row", muscle: "Shoulders", equipment: "Barbell", level: "Intermediate" },
    { id: "e47", name: "Shrugs", muscle: "Shoulders", equipment: "Dumbbell", level: "Beginner" },
    { id: "e48", name: "Barbell Shrugs", muscle: "Shoulders", equipment: "Barbell", level: "Intermediate" },

    // Legs
    { id: "e49", name: "Barbell Squat", muscle: "Legs", equipment: "Barbell", level: "Intermediate" },
    { id: "e50", name: "Front Squat", muscle: "Legs", equipment: "Barbell", level: "Advanced" },
    { id: "e51", name: "Goblet Squat", muscle: "Legs", equipment: "Dumbbell", level: "Beginner" },
    { id: "e52", name: "Leg Press", muscle: "Legs", equipment: "Machine", level: "Beginner" },
    { id: "e53", name: "Romanian Deadlift", muscle: "Legs", equipment: "Barbell", level: "Intermediate" },
    { id: "e54", name: "Stiff Leg Deadlift", muscle: "Legs", equipment: "Dumbbell", level: "Intermediate" },
    { id: "e55", name: "Walking Lunges", muscle: "Legs", equipment: "Dumbbell", level: "Beginner" },
    { id: "e56", name: "Bulgarian Split Squat", muscle: "Legs", equipment: "Dumbbell", level: "Intermediate" },
    { id: "e57", name: "Leg Extension", muscle: "Legs", equipment: "Machine", level: "Beginner" },
    { id: "e58", name: "Leg Curl", muscle: "Legs", equipment: "Machine", level: "Beginner" },
    { id: "e59", name: "Standing Calf Raise", muscle: "Legs", equipment: "Machine", level: "Beginner" },
    { id: "e60", name: "Seated Calf Raise", muscle: "Legs", equipment: "Machine", level: "Intermediate" },
    { id: "e61", name: "Bodyweight Squat", muscle: "Legs", equipment: "Bodyweight", level: "Beginner" },
    { id: "e62", name: "Jump Squat", muscle: "Legs", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e63", name: "Pistol Squat", muscle: "Legs", equipment: "Bodyweight", level: "Advanced" },
    { id: "e64", name: "Glute Bridge", muscle: "Legs", equipment: "Bodyweight", level: "Beginner" },
    { id: "e65", name: "Barbell Hip Thrust", muscle: "Legs", equipment: "Barbell", level: "Intermediate" },
    { id: "e66", name: "Box Jumps", muscle: "Legs", equipment: "Bodyweight", level: "Intermediate" },

    // Arms
    { id: "e67", name: "Barbell Curl", muscle: "Arms", equipment: "Barbell", level: "Beginner" },
    { id: "e68", name: "EZ Bar Curl", muscle: "Arms", equipment: "Barbell", level: "Beginner" },
    { id: "e69", name: "Dumbbell Curl", muscle: "Arms", equipment: "Dumbbell", level: "Beginner" },
    { id: "e70", name: "Hammer Curl", muscle: "Arms", equipment: "Dumbbell", level: "Beginner" },
    { id: "e71", name: "Incline Dumbbell Curl", muscle: "Arms", equipment: "Dumbbell", level: "Intermediate" },
    { id: "e72", name: "Concentration Curl", muscle: "Arms", equipment: "Dumbbell", level: "Beginner" },
    { id: "e73", name: "Cable Curl", muscle: "Arms", equipment: "Cable", level: "Beginner" },
    { id: "e74", name: "Preacher Curl", muscle: "Arms", equipment: "Machine", level: "Intermediate" },
    { id: "e75", name: "Triceps Pushdown", muscle: "Arms", equipment: "Cable", level: "Beginner" },
    { id: "e76", name: "Rope Triceps Pushdown", muscle: "Arms", equipment: "Cable", level: "Beginner" },
    { id: "e77", name: "Overhead Triceps Extension", muscle: "Arms", equipment: "Dumbbell", level: "Beginner" },
    { id: "e78", name: "Skullcrusher", muscle: "Arms", equipment: "Barbell", level: "Intermediate" },
    { id: "e79", name: "Triceps Dip", muscle: "Arms", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e80", name: "Close Grip Bench Press", muscle: "Arms", equipment: "Barbell", level: "Intermediate" },
    { id: "e81", name: "Diamond Push-Up", muscle: "Arms", equipment: "Bodyweight", level: "Intermediate" },

    // Core
    { id: "e82", name: "Crunch", muscle: "Core", equipment: "Bodyweight", level: "Beginner" },
    { id: "e83", name: "Reverse Crunch", muscle: "Core", equipment: "Bodyweight", level: "Beginner" },
    { id: "e84", name: "Hanging Leg Raise", muscle: "Core", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e85", name: "Hanging Knee Raise", muscle: "Core", equipment: "Bodyweight", level: "Beginner" },
    { id: "e86", name: "Plank", muscle: "Core", equipment: "Bodyweight", level: "Beginner" },
    { id: "e87", name: "Side Plank", muscle: "Core", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e88", name: "Cable Crunch", muscle: "Core", equipment: "Cable", level: "Beginner" },
    { id: "e89", name: "Russian Twist", muscle: "Core", equipment: "Bodyweight", level: "Beginner" },
    { id: "e90", name: "Bicycle Crunch", muscle: "Core", equipment: "Bodyweight", level: "Beginner" },
    { id: "e91", name: "Ab Wheel Rollout", muscle: "Core", equipment: "Machine", level: "Advanced" },
    { id: "e92", name: "Dragon Flag", muscle: "Core", equipment: "Bodyweight", level: "Advanced" },
    { id: "e93", name: "Dead Bug", muscle: "Core", equipment: "Bodyweight", level: "Beginner" },
    { id: "e94", name: "V-Ups", muscle: "Core", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e95", name: "Mountain Climbers", muscle: "Core", equipment: "Bodyweight", level: "Beginner" },

    // Cardio
    { id: "e96", name: "Treadmill Run", muscle: "Cardio", equipment: "Machine", level: "Beginner" },
    { id: "e97", name: "Treadmill Sprint", muscle: "Cardio", equipment: "Machine", level: "Advanced" },
    { id: "e98", name: "Rowing Machine", muscle: "Cardio", equipment: "Machine", level: "Beginner" },
    { id: "e99", name: "Jump Rope", muscle: "Cardio", equipment: "Bodyweight", level: "Beginner" },
    { id: "e100", name: "Stationary Bike", muscle: "Cardio", equipment: "Machine", level: "Beginner" },
    { id: "e101", name: "Stairmaster", muscle: "Cardio", equipment: "Machine", level: "Intermediate" },
    { id: "e102", name: "Burpees", muscle: "Cardio", equipment: "Bodyweight", level: "Intermediate" },
    { id: "e103", name: "Assault Bike", muscle: "Cardio", equipment: "Machine", level: "Advanced" },
    { id: "e104", name: "Elliptical", muscle: "Cardio", equipment: "Machine", level: "Beginner" },
    { id: "e105", name: "Jumping Jacks", muscle: "Cardio", equipment: "Bodyweight", level: "Beginner" }
];

// Exporting if it's used as a module, or just attaching to window
if (typeof module !== 'undefined' && module.exports) {
    module.exports = exerciseDB;
} else if (typeof window !== 'undefined') {
    window.exerciseDB = exerciseDB;
}
